### ISSUE TITLE
Issues launching with instructions given for Edge

### ISSUE THREAD

**Issue by Leopere** [gbrks/docker-syncthing#4]
# Issues with edge

With your example for Edge it fails and loops.

```
[start] 19:02:57 INFO: Generating RSA key and certificate for syncthing...
[start] 19:02:58 FATAL: save cert: open /config/cert.pem: permission denied
19:03:00 WARNING: chmod /config: operation not permitted
[start] 19:03:00 INFO: Generating RSA key and certificate for syncthing...
[start] 19:03:02 FATAL: save cert: open /config/cert.pem: permission denied
19:03:05 WARNING: chmod /config: operation not permitted
[start] 19:03:05 INFO: Generating RSA key and certificate for syncthing...
[start] 19:03:07 FATAL: save cert: open /config/cert.pem: permission denied
```
## My config

```
docker run -d --name=syncthing \
  --restart=on-failure:20 \
  -v ./appdata/syncthing:/config \
  -v ./data/:/sync/data/ \
  -p 8384:8384/tcp \
  -p 22000:22000/tcp \
  -p 21025:21025/udp \
  gbrks/syncthing:edge
```

**Comment by gbrks** [comment]
What are your permissions for ./appdata/syncthing?
They should be read/writable by the host user with uid 1000

**Comment by Leopere** [comment]
So far whatever the container comes with, but I will take that into account next time I get the chance.  Maybe if its permissions are so fragile the container could enforce file permissions on boot?

**Comment by gbrks** [comment]
That directory is not in the container, it is the folder on your host.

The container runs as user 1000 (which will generally be your default user). That user needs rw access to that directory.

You should also be using full paths rather than relative, eg /home/chamunks/appears/syncthing (or where ever you wish to store the config).

It is also possible to run the container as root by including -u="root" in the docker run command, however ownership of the config files will taken by root.

There is an open issue (https://github.com/gbrks/docker-syncthing/issues/2) to update the image to allow nomination of different user during container creation (in case you need to run as a user other than 1000). I can progress this issue if there is need for it.

**Comment by Leopere** [comment]
Ah thank you for all of this great information I had an issue with file permissions similar to this in a MySQL container earlier this year turns out that specifically MySQL just absolutely will not operate with the wrong ownership let alone permissions as well.

Would you be interested in a PR with some more documentation in your README to cover this issue or will/can you update it.

**Comment by Hyzual** [comment]
Thank you for making this image, it works great !
Just so you know, I was trying to use named volumes with this image and encountered the same issue with permissions. To solve it I had to run the container with `--user="root"`
I'll list the commands I ran here just for reference:

``` bash
sudo docker volume create --name syncthing-config
sudo docker volume create --name syncthing-data
sudo docker run -d --name=syncthing \
    --restart=on-failure:20 \
    -v syncthing-config:/config \
    -v syncthing-data:/sync \
    --user="root" \
    -p 8384:8384/tcp \
    -p 22000:22000/tcp \
    -p 21025:21025/udp \
    gbrks/syncthing:latest
```

**Comment by gbrks** [comment]
Hi,
One way you could solve this, would be to `exec` into your container, and change the ownership of the /config and /sync directories (and therefore the volumes) to what UID you needed. 
Then destroy and re-create the container using the user you wanted.

However to be honest, I would recommend trying out the image made by the guys at Linuxserver.io
https://hub.docker.com/r/linuxserver/syncthing/

Well maintained, and allows you to easily apply whatever user/group you need to.

I made this container, based on Alpine, because I wanted a lean image for syncthing. Since then, linuxserver.io have produced some fantastic images, and I've found myself running a few of them, so there doesnt end up being any additional overhead by using the linuxserver/syncthing image in this case.

**Comment by Hyzual** [comment]
Hi, thanks, in fact it did work once I ran with `--user="root"`. I tried the linuxserver image before but yours is smaller and works just as well, so I'll be using it :)
